sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - '10'
before_install:
  - 'npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN'
jobs:
  include:
    - stage: release
      if: "((type = push AND branch = master) OR type = pull_request) AND NOT commit_message =~ /\\[autorelease\\]/"
      script:
        - npm test
        - npm run autorelease -- --expanded --no-skip-build
    - stage: message-duty
      if: 'type = cron AND branch = master'
      script:
        - node .ci/assign-issue.js
branches:
  only:
    - "master"
deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GH_TOKEN
  verbose: true
  on:
    branch: master
